exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex("messages")
    .truncate()
    .then(function () {
      // Inserts seed entries
      return knex("messages").insert([
        {
          id: 1,
          messageText: "1st message test",
          userId: 1,
          chatId: 1,
        },
        {
          id: 2,
          messageText: "2nd message test",
          userId: 2,
          chatId: 1,
        },
        {
          id: 3,
          messageText: "3rd message test",
          userId: 1,
          chatId: 2,
        },
        {
          id: 4,
          messageText: "4th message test",
          userId: 3,
          chatId: 2,
        },
        {
          id: 5,
          messageText: "5th message test",
          userId: 1,
          chatId: 3,
        },
        {
          id: 6,
          messageText: "6th message test",
          userId: 4,
          chatId: 3,
        },
        {
          id: 7,
          messageText: "7th message test",
          userId: 2,
          chatId: 4,
        },
        {
          id: 8,
          messageText: "8th message test",
          userId: 5,
          chatId: 4,
        },
        {
          id: 9,
          messageText: "9th message test",
          userId: 2,
          chatId: 5,
        },
        {
          id: 10,
          messageText: "10th message test",
          userId: 6,
          chatId: 5,
        },
        {
          id: 11,
          messageText: "11th message test",
          userId: 2,
          chatId: 6,
        },
        {
          id: 12,
          messageText: "12th message test",
          userId: 7,
          chatId: 6,
        },
        {
          id: 13,
          messageText: "13th message test",
          userId: 3,
          chatId: 7,
        },
        {
          id: 14,
          messageText: "14th message test",
          userId: 8,
          chatId: 7,
        },
        {
          id: 15,
          messageText: "15th message test",
          userId: 3,
          chatId: 8,
        },
        {
          id: 16,
          messageText: "16th message test",
          userId: 2,
          chatId: 8,
        },
        {
          id: 17,
          messageText: "17th message test",
          userId: 3,
          chatId: 9,
        },
        {
          id: 18,
          messageText: "18th message test",
          userId: 4,
          chatId: 9,
        },
        {
          id: 19,
          messageText: "19th message test",
          userId: 4,
          chatId: 10,
        },
        {
          id: 20,
          messageText: "20th message test",
          userId: 5,
          chatId: 10,
        },
        {
          id: 21,
          messageText: "21th message test",
          userId: 4,
          chatId: 11,
        },
        {
          id: 22,
          messageText: "22th message test",
          userId: 6,
          chatId: 11,
        },
        {
          id: 23,
          messageText: "23th message test",
          userId: 4,
          chatId: 12,
        },
        {
          id: 24,
          messageText: "24th message test",
          userId: 7,
          chatId: 12,
        },
        {
          id: 25,
          messageText: "25th message test",
          userId: 5,
          chatId: 13,
        },
        {
          id: 26,
          messageText: "26th message test",
          userId: 8,
          chatId: 13,
        },
        {
          id: 27,
          messageText: "27th message test",
          userId: 5,
          chatId: 14,
        },
        {
          id: 28,
          messageText: "28th message test",
          userId: 3,
          chatId: 14,
        },
        {
          id: 29,
          messageText: "29th message test",
          userId: 5,
          chatId: 15,
        },
        {
          id: 30,
          messageText: "30th message test",
          userId: 4,
          chatId: 15,
        },
        {
          id: 31,
          messageText: "31th message test",
          userId: 6,
          chatId: 16,
        },
        {
          id: 32,
          messageText: "32th message test",
          userId: 5,
          chatId: 16,
        },
        {
          id: 33,
          messageText: "33th message test",
          userId: 6,
          chatId: 17,
        },
        {
          id: 34,
          messageText: "34th message test",
          userId: 7,
          chatId: 17,
        },
        {
          id: 35,
          messageText: "35th message test",
          userId: 6,
          chatId: 18,
        },
        {
          id: 36,
          messageText: "36th message test",
          userId: 8,
          chatId: 18,
        },
        {
          id: 37,
          messageText: "37th message test",
          userId: 7,
          chatId: 19,
        },
        {
          id: 38,
          messageText: "38th message test",
          userId: 3,
          chatId: 19,
        },
        {
          id: 39,
          messageText: "39th message test",
          userId: 7,
          chatId: 20,
        },
        {
          id: 40,
          messageText: "40th message test",
          userId: 8,
          chatId: 20,
        },
        {
          id: 41,
          messageText: "41th message test",
          userId: 7,
          chatId: 21,
        },
        {
          id: 42,
          messageText: "42th message test",
          userId: 5,
          chatId: 21,
        },
        {
          id: 43,
          messageText: "43th message test",
          userId: 8,
          chatId: 22,
        },
        {
          id: 44,
          messageText: "44th message test",
          userId: 1,
          chatId: 22,
        },
        {
          id: 45,
          messageText: "45th message test",
          userId: 8,
          chatId: 23,
        },
        {
          id: 46,
          messageText: "46th message test",
          userId: 4,
          chatId: 23,
        },
        {
          id: 47,
          messageText: "47th message test",
          userId: 8,
          chatId: 24,
        },
        {
          id: 48,
          messageText: "48th message test",
          userId: 3,
          chatId: 24,
        },
      ]);
    });
};
